# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfMuseumShips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('from_country', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('ship_class', models.CharField(max_length=250)),
                ('ship_type', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=250)),
            ],
        ),
    ]
