# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcoordinates',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shipcoordinates',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
