# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipimage',
            old_name='url',
            new_name='source_url',
        ),
        migrations.AddField(
            model_name='shipimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
