# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmuseumships',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='listofmuseumships',
            name='region',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='listofmuseumships',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='listofmuseumships',
            name='ship_class',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='listofmuseumships',
            name='ship_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
