# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170718_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfMuseumShips',
            new_name='ShipList',
        ),
    ]
