# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171014_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipimage',
            name='ship_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.ShipList'),
        ),
    ]
