# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171014_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipimage',
            old_name='ship_details',
            new_name='ship',
        ),
    ]
