# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170718_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ShipList')),
            ],
        ),
        migrations.CreateModel(
            name='ShipImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_description', models.TextField(blank=True)),
                ('artist', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('usage_terms', models.CharField(max_length=250)),
                ('license_url', models.URLField()),
                ('license_short_name', models.CharField(max_length=200)),
                ('ship_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_details', to='core.ShipDetails')),
            ],
        ),
    ]
