# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shipdetails_shipimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipdetails',
            name='ship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.ShipList'),
        ),
    ]
